import type { CatalogConfig } from "../types";

export const catalogConfigs: CatalogConfig[] = [
  {
    key: "modelos",
    label: "Modelos",
    singularLabel: "modelo",
    hasImage: true,
    hasColor: false,
    hasPriceModifier: false,
    description: "Define los estilos y diseños de pijamas disponibles.",
  },
  {
    key: "telas",
    label: "Telas",
    singularLabel: "tela",
    hasImage: true,
    hasColor: false,
    hasPriceModifier: true,
    description: "Gestiona las telas disponibles para cada modelo.",
  },
  {
    key: "colores",
    label: "Colores",
    singularLabel: "color",
    hasImage: false,
    hasColor: true,
    hasPriceModifier: false,
    description: "Configura los colores que pueden combinarse.",
  },
  {
    key: "estampados",
    label: "Estampados",
    singularLabel: "estampado",
    hasImage: true,
    hasColor: false,
    hasPriceModifier: true,
    description: "Administra los estampados disponibles en la colección.",
  },
  {
    key: "bordados",
    label: "Bordados",
    singularLabel: "bordado",
    hasImage: true,
    hasColor: false,
    hasPriceModifier: true,
    description: "Configura los diseños de bordados y sus ubicaciones.",
  },
  {
    key: "tallas",
    label: "Tallas",
    singularLabel: "talla",
    hasImage: false,
    hasColor: false,
    hasPriceModifier: false,
    description: "Define las tallas disponibles para cada modelo.",
  },
];